### ISSUE TITLE
An error occurred when mapping the model through YAML configuration：  [Errno 2] No such file or directory: '/ComfyUI/models/sonic/RIFE/flownet.pkl'

### ISSUE THREAD

**Issue by ChangeDevelop** [smthemex/ComfyUI_Sonic#94]
I encountered a problem while using it. An error occurred during the running process: **### [Errno 2] No such file or directory: '/ComfyUI/models/sonic/RIFE/flownet.pkl'**
1. I use Tencent Cloud for building.
2. The comfyUI package is in **/ComfyUI**.
3. The model package is in **/workspace/models**.
4. Start it with the following command. 
```
python /ComfyUI/main.py \
  --listen 0.0.0.0 \
  --auto-launch \
  --extra-model-paths-config /workspace/extra_model_paths.yaml 
```
```
# extra_model_paths.yaml
comfyui:
    base_path: /workspace/models/
    checkpoints: checkpoints/
    clip: clip/
    clip_vision: clip_vision/
    text_encoders: text_encoders/
    configs: configs/
    controlnet: controlnet/
    diffusion_models: |
                 diffusion_models
                 unet
    embeddings: embeddings/
    loras: loras/
    upscale_models: upscale_models/
    vae: vae/
other_ui:
    sonic: /workspace/models/sonic/
```
5. I also tried to connect the model through a soft link, but it didn't work: 
`ln -s /workspace/models/sonic /ComfyUI/models/sonic `
My project package address: [https://cnb.cool/aicg-plus/comfyui-main](https://cnb.cool/aicg-plus/comfyui-main)
My issue is:
Must the model be placed in /ComfyUI/models? Or is there any other issue?
